data:
  task: binder_motif   # * hallucination, inpainting，binder, binder_rotamer, binder_motif
  dataset: ppi
  loader:
    num_workers: 4 # 4
    prefetch_factor: 10
  sampler:
    max_batch_size: 20
    max_num_res_squared: 400000
    batch_repeats: 2
interpolant:
  min_t: 0.01
  separate_t: false
  provide_kappa: false
  hierarchical_t: false
  dynamic_t_method: # *xk: dynamic
    intervals: [ [ 0, 0.25 ], [ 0.25, 0.5 ], [ 0.5, 0.75 ], [ 0.75, 1.0 ] ]
    initial_probs: [ 0.25, 0.25, 0.25, 0.25 ]
    final_probs: [ 0.6, 0.2, 0.1, 0.1 ]
    max_epochs: ${experiment.trainer.max_epochs}
  piecewise_t_method: # *xk: piecewise   dynamic_t
    intervals: [ [ 0, 0.25 ], [ 0.25, 0.5 ], [ 0.5, 0.75 ], [ 0.75, 1.0 ] ]
    probs: [ [ 0.6, 0.2, 0.1, 0.1 ], [ 0.75, 0.15, 0.05, 0.05 ] ]
    start_epochs: [ 60, 100 ]    # * add-mono
  twisting:
    use: false
  starting_at_hotspot_center: false   # *
  rots:
    corrupt: true
    train_schedule: linear
    sample_schedule: exp
    exp_rate: 10
  trans:
    corrupt: true
    var_scale: 10        # *
    batch_ot: true
    train_schedule: linear
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: false
    rog:
      weight: 10.0
      cutoff: 5.0
  sampling:
    num_timesteps: 100  # *
    do_sde: false
  self_condition: ${model.edge_features.self_condition}
folding:
  seq_per_sample: 8
  own_device: false
  folding_model: esmf
  pmpnn_path: ./ProteinMPNN/
  pt_hub_dir: ./.cache/torch/
experiment:
  debug: False
  recording_trajectory: last     # debug
  seed: 123
  num_devices: 1     # * gpu num
  warm_start: null
  warm_start_cfg_override: false
  training:
    mask_plddt: true
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0    # * originally 2.0,  3.0 is the normal scale
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0          # * 1.0
    aux_loss_use_bb_loss: 1.0
    aux_loss_use_pair_loss: 1.0
    aux_loss_use_clash_loss: 0.0    # *
    aux_loss_use_interchain_clash_loss: 0.0   # *
    aux_loss_use_center_mse_loss: 0.0   # *
    aux_loss_use_interface_loss: 1.0  # **  1
    ca_clash_tolerance: 1.2
    interchain_clash_tolerance: 2.0
    aux_loss_t_pass: 0.5    # * 0.5
    pair_loss_use_hotspot_loss: false    # **
    trans_loss_clamp: 5 # #old:5
    auxiliary_loss_clamp: 5 # #old:5
    use_seq_loss: false     # *
    seq_loss_weight: 1.0   # *
    seq_loss_clamp: 5
  wandb:
    name: ${data.task}_${data.dataset}
    project: se3-fm
    save_code: true
    mode: offline
    save_dir: ${experiment.checkpointer.dirpath}/..
    dir: ${experiment.checkpointer.dirpath}/..
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 1
    max_epochs: 1000 #1000 ，4 for debug
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: false
    strategy: ddp #ddp:多机多卡， dp：单机多卡， #ddp_find_unused_parameters_true
    num_nodes: 1 #节点数
    check_val_every_n_epoch: 1  # *
    accumulate_grad_batches: 4  # * 2
    enable_progress_bar: True

  checkpointer:
    dirpath: results/${experiment.wandb.name}/${now:%Y%m%d}/${now:%H_%M_%S}/ckpt
#    save_last: True
    save_top_k: -1
    monitor: valid/trans_loss/dataloader_idx_0  # valid/bb_rmsd    # add-monomer
    mode: max # min
  pretrain_path: experiments/results/binder_motif_ppi/20250329/22_19_38/ckpt/epoch=92-step=71889.ckpt

  testing_model: # **
    save_dir: sample_result/${experiment.wandb.name}/${now:%Y%m%d}/${now:%H_%M_%S}/sample_test
    ckpt_path:  "epoch-step=80367.ckpt"
shared:
  seed: 123
  max_cache_size: 100000
  samples_per_eval_length: 5
  num_eval_lengths: 8
  max_eval_length: 256
  min_motif_percent: 0.05
  max_motif_percent: 0.5


ppi_dataset:      # **
  seed: ${shared.seed}
#  sample_pdbname: None
  train_csv_path:  processed_ppi/filtered_train_metadata20241015_a.csv
  val_csv_path:  processed_ppi/filtered_val_metadata20241015_a.csv
  test_csv_path:  metadata/motif_test7.csv

  samples_min_hotspots: 3
  min_hotspot_ratio: 0.2    # *
  max_hotspot_ratio: 0.5
  motif:
    define_motif: false #used in sample, if True: use all motif ; False: sample 1~len(motif_list)-1 as motif # **

  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 0
  add_plddt_mask: False
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_min_length: 60 # **  50
  samples_max_length: 90 # **  100
  samples_per_target: 100 # **   debug
  samples_batch_size: 1 # **
  sample_original_binder_len: False # **
  sample_pdbname: null

  filter:
    max_coil_percent: 0.5
    rog_quantile: 0.99


model:
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: false
  # xk
  use_gradient_checkpointing: True   # *
  use_deepspeed_evo_attention: False   # *
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    c_aatype_emb: 128
    max_num_res: 2000
    timestep_int: 1000
    embed_chain: true
    embed_aatype: true
    n_aatype: 22
  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    feat_dim: 64
    rel_pos_feat_dim: 64
    num_bins: 22
    self_condition: true
    embed_chain: true
    embed_diffuse_mask: true
    embed_hotspot_mask: true # True, False
    embed_aatype: true
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6
  seq_decoder:
    use: false    # *
    c_s: ${model.node_embed_size}
    feat_dim: 128
  pairformer:
    use: true
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    no_heads: 8
    num_blocks: 4   # *
    c_hidden_pair_att: 16
    no_heads_pair: 4
